/** One warm, learning-flavoured phrase per nakshatra, in order (Ashwini..Revati). */
export const NAKSHATRA_THEMES: string[] = [
  "quick starts and a pioneering curiosity",
  "steady persistence and a love of doing things thoroughly",
  "sharp focus once something has captured their interest",
  "gentle sensory learning and a love of comfort and beauty",
  "restless energy and a drive to explore and investigate",
  "an emotional, intense way of processing new ideas",
  "warmth, sociability, and learning well alongside others",
  "quiet resilience and comfort with structure",
  "an intuitive, sometimes dreamy way of absorbing ideas",
  "bold self-belief and a taste for leadership",
  "a love of connection, fairness, and creative play",
  "conscientiousness and pride in doing careful work",
  "practical skill, dexterity, and hands-on cleverness",
  "an eye for beauty, craft, and expressive detail",
  "adaptability and comfort with change and new situations",
  "a drive to achieve and to be recognised for effort",
  "loyalty, balance, and quiet emotional depth",
  "sharp, sometimes intense analytical instincts",
  "deep-diving curiosity and comfort with hard questions",
  "invincible determination once they've decided something matters",
  "quiet leadership and a strong sense of purpose",
  "attentive listening and a love of learning from others",
  "cheerful resourcefulness and a knack for practical problem-solving",
  "an inventive, independent-minded streak",
  "expansive imagination and optimism",
  "a strong inner compass and quiet steadiness",
  "gentle empathy and a rich inner, imaginative world",
];
